package com.asdco.nas.util;

import java.util.List;

import javax.inject.Inject;

import com.asdco.nas.dao.NasServer;

public class NasServerUtil {
	
	@Inject
	JpaUtil jpaUtil;

	public String registerServer(NasServer newServer) {
		jpaUtil.persist(newServer);
		
		//after the entity gets persisted and the transaction completed, the java bean will contain the ID generated by the server
		return "Your server id is " + newServer.getId();
	}

	public List<NasServer> getAllServers() {
		return jpaUtil.executeGetNamedQuery("NasServer.findAll", null, NasServer.class);
	}
	
}
