package com.asdco.nas.util;


import java.util.Calendar;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.inject.Inject;
import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.PathParam;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;

import com.asdco.nas.dao.HeartbeatLog;
import com.asdco.nas.dao.NasServer;


public class NasServerUtil {
	
	@Inject
	JpaUtil jpaUtil;

	public String registerServer(NasServer serverToRegister) {
		jpaUtil.persist(serverToRegister);
		
		//after the entity gets persisted and the transaction completed, the java bean will contain the ID generated by the server
		return "Your server id is " + serverToRegister.getId();
	}
	

	public NasServer getServerByName (String name){
		List<NasServer> serverList;
		HashMap<String, Object> requestedName = new HashMap<String, Object>();
		requestedName.put("name",name);
		serverList = jpaUtil.executeGetNamedQuery ("NasServer.findByName",requestedName,NasServer.class);
		return serverList.get(0);
	}

	

	public String addServer(String name) {
		NasServer entry = new NasServer();
		return (registerServer(entry));
		//return "The server "+name+" has been added. Server ID is .";
	}

	public List<NasServer> getAllServers() {
		return jpaUtil.executeGetNamedQuery("NasServer.findAll", null, NasServer.class);
	}
	
}
