package com.asdco.nas.util;

import java.util.Calendar;
import java.util.List;

import javax.inject.Inject;

import com.asdco.nas.dao.HeartbeatLog;
import com.asdco.nas.dao.NasServer;

public class NasServerUtil {
	
	@Inject
	JpaUtil jpaUtil;

	public String registerServer(NasServer newServer) {
		jpaUtil.persist(newServer);
		
		//after the entity gets persisted and the transaction completed, the java bean will contain the ID generated by the server
		return "Your server id is " + newServer.getId();
	}
	
	private Long NasServer(Long serverId) {
		//create a new server entry
		NasServer entry = new NasServer();

		//add the server id that was provided by the client in the GET request e
		entry.setId(serverId);

		//save it to the database
		jpaUtil.persist(entry);
		
		return entry.getId();
	}

	public List<NasServer> getAllServers() {
		return jpaUtil.executeGetNamedQuery("NasServer.findAll", null, NasServer.class);
	}
	
}
